
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SEGUN = 10;
  public static final int MENOS = 24;
  public static final int CADENA = 28;
  public static final int TIPO_TEXTO = 16;
  public static final int ROMPER = 13;
  public static final int DECIMAL = 30;
  public static final int DEFECTO = 12;
  public static final int IMPRIMIR = 5;
  public static final int TIPO_ENTERO = 14;
  public static final int PARENTESIS_IZQ = 20;
  public static final int PARA = 9;
  public static final int PARENTESIS_DER = 21;
  public static final int DOS_PUNTOS = 19;
  public static final int COMA = 22;
  public static final int CASO = 11;
  public static final int ASIGNACION = 17;
  public static final int MULT = 25;
  public static final int EOF = 0;
  public static final int SINO = 7;
  public static final int DIV = 26;
  public static final int SI = 6;
  public static final int error = 1;
  public static final int TIPO_DECIMAL = 15;
  public static final int IDENTIFICADOR = 27;
  public static final int ENTERO = 29;
  public static final int MIENTRAS = 8;
  public static final int FIN = 3;
  public static final int MAS = 23;
  public static final int VAR = 4;
  public static final int PUNTO_Y_COMA = 18;
  public static final int INICIO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "IMPRIMIR",
  "SI",
  "SINO",
  "MIENTRAS",
  "PARA",
  "SEGUN",
  "CASO",
  "DEFECTO",
  "ROMPER",
  "TIPO_ENTERO",
  "TIPO_DECIMAL",
  "TIPO_TEXTO",
  "ASIGNACION",
  "PUNTO_Y_COMA",
  "DOS_PUNTOS",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "COMA",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "IDENTIFICADOR",
  "CADENA",
  "ENTERO",
  "DECIMAL"
  };
}

