package Analizador;

public enum TokenType {
    PALABRA_RESERVADA, TIPO_DATO, IDENTIFICADOR, ENTERO, DECIMAL, CADENA,
    OPERADOR, ASIGNACION, PUNTO_Y_COMA, PARENTESIS_IZQ, PARENTESIS_DER, COMA, DESCONOCIDO
}
